server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: discord-db
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      maximum-pool-size: 1
    url: jdbc:postgresql://${db}/discordbot
    driver-class-name: org.postgresql.Driver
    username: bot
    password: ${pw}
    initialization-mode: always